### ISSUE TITLE
I hate to be that guy...

### ISSUE THREAD

**Issue by bwheeler96** [laurihy/angular-payments#44]
but it seems like a total "gotcha" that declaring

`stripe-form="functionName"`

without the `()`, is undocumented, I think it would be better if this were explicitly states IMHO.

And thanks for the awesome plugin! Saving me tons of time! I'll definitely contribute if I think I can do something useful!

**Comment by MichaelJCole** [comment]
It's documented here now in the example.  Good enough?
 
https://github.com/laurihy/angular-payments#stripeform
