### ISSUE TITLE
Make Editing error messages so obvious.

### ISSUE THREAD

**Issue by nigeltiany** [laurihy/angular-payments#99]
Default error messages for card and cvc are please enter card error and please enter cvc error. Information on how to change this would be great to have on this wiki/project homepage. Plus it would be a good idea if it came out the box with slightly in context error messages e.g. For card error - Please enter a valid card number. For cvc error - Invalid CVC number.

**Comment by Nigeltiany** [comment]
`app.run(function (defaultErrorMessageResolver) {
    defaultErrorMessageResolver.getErrorMessages().then(function (errorMessage) {
        errorMessage['invalidPhoneNumber'] = 'Please enter a valid phone number';
        errorMessage['card'] = 'Please enter a valid card number';
        errorMessage['cvc'] = 'Invalid CVC';
    });
});`
